### ISSUE TITLE
Even with the special Movian Build it gives a 404

### ISSUE THREAD

**Issue by Invictaz** [LFriede/movian-dmax#1]
Even with this special build:

https://doozer.io/andoma/movian/build/734

which is according to the two commits merged:

https://github.com/andoma/movian/pull/230

from https://github.com/andoma/movian/pull/230/commits/e41b35943be08e402aaa7bdf1a685b572093261a

It still does not play, gives a 404. 

Is the page changed?

**Comment by LFriede** [comment]
I'll take a look later when i'm at home. The 0.1 version on release page is outdated, did you try the master branch or the old release?

**Comment by LFriede** [comment]
They changed the API, i'm working on a fix.

**Comment by Invictaz** [comment]
I have the 0.2 version now from master branch. Still does not work. I tried it with the special Movian build which has the http post content type.

**Comment by LFriede** [comment]
You can use any Movian build, the one with the post patch was just needed for the first version of the dmax plugin. This is not required anymore.

**Comment by Invictaz** [comment]
That's good news. Here is a new log with the error clearly seen. HTTP 404 page not found on an API request

https://pastebin.com/5hyVuu29

**Comment by LFriede** [comment]
Everything should be fixed now, please try the new changes.

**Comment by Invictaz** [comment]
@LFriede it's geoblocked so I use a VPN with a German IP but it still does not retrieve the correct token

21:12:51.758 index.html:1 HTTP            [DEBUG]:: Connection to sonic-eu1-prod.disco-api.com:443 failed -- Unable to connect -- No access
21:12:51.758 index.html:1 dmax            [ERROR]:: Error (HTTP request failed https://sonic-eu1-prod.disco-api.com/playback/videoPlaybackInfo/39354 -- Unable to connect -- No acce...
21:12:51.758 index.html:1 dmax            [ERROR]:: STACK DUMP: Error: HTTP request failed https://sonic-eu1-prod.disco-api.com/playback/videoPlaybackInfo/39354 -- Unable to connec...
21:12:51.758 index.html:1                         :     at [anon] (/home/andoma/src/movian/src/ecmascript/es_io.c:430) internal
21:12:51.758 index.html:1                         :     at light_00421a80_0003 light strict preventsyield
21:12:51.758 index.html:1                         :     at [anon] (showtime/http:103)
21:12:51.758 index.html:1                         :     at [anon] (zip://persistent:///persistent/installedplugins/dmax.zip/dmax.js:18) preventsyield
21:12:51.759 index.html:1                         :     at apply () native strict preventsyield
21:12:51.759 index.html:1                         :     at [anon] (showtime/page:396) preventsyield

https://i.imgur.com/Smmykqi.png

Logfile

https://pastebin.com/s1UyH5hh

**Comment by LFriede** [comment]
Okay this looks like another problem... that "no access" message is weird, seems like there is not even a header going out. I'll have a deeper look at this, later.

**Comment by Invictaz** [comment]
@LFriede Do you need more information?

**Comment by LFriede** [comment]
No, just give me some time ;)

**Comment by LFriede** [comment]
Sorry, but i am not able to reproduce that connection error. I tried PS3, Android, Linux and Chrome version. I tried wired and 4G but it works every time i try.
Which vpn provider do you use? Is it free?

**Comment by Invictaz** [comment]
Tunnelbear, considered one of the better. Even with Ghostbear, which masks the traffic with an extra encryption layer so that it seems normal traffic. Maybe they have VPN detection? Can you try it with a different IP (via VPN) and see if that is the problem?

**Comment by Invictaz** [comment]
Test


-------- Oorspronkelijk bericht --------
Van: gordon-- <notifications@github.com>
Datum: 11-03-18 17:07 (GMT+01:00)
Aan: LFriede/movian-dmax <movian-dmax@noreply.github.com>
Cc: Invictaz <jrkonings@hotmail.com>, Author <author@noreply.github.com>
Onderwerp: Re: [LFriede/movian-dmax] Even with the special Movian Build it gives a 404 (#1)


Sorry, but i am not able to reproduce that connection error. I tried PS3, Android, Linux and Chrome version. I tried wired and 4G but it works every time i try.
Which vpn provider do you use? Is it free?

**Comment by LFriede** [comment]
I will try it with VPN to check if this is the problem.

**Comment by LFriede** [comment]
I've downloaded Tunnelbear, I am not able to watch streams with it, even with german VPN ip it says I'm geoblocked. But i don't get the "no access" error like in your log, I am getting a 403 response from the server which is not the case in your log.

**Comment by Invictaz** [comment]
Interesting, the other log file I provided you earlier gave the 403 error for me as well. So it seems that not all VPN providers work. If I try another VPN maybe it works. 

No access could also mean geoblocked

**Comment by Invictaz** [comment]
@LFriede I submitted a ticket about this with Tunnelbear, now bought by McAfee as one of the bigger VPN services. I hope they will respond. Otherwise I'm going to uninstall and try another VPN.
